version: '3.8'

services:

  wordpress:
    image: wordpress:6.5.4-php8.2-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: 'exampleuser'
      WORDPRESS_DB_PASSWORD: 'examplepass'
      WORDPRESS_DB_NAME: 'wordpress'
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html

  db:
    image: mariadb:12.0.1-ubi9-rc
    restart: always
    environment:
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'exampleuser'
      MYSQL_PASSWORD: 'examplepass'
      MYSQL_ROOT_PASSWORD: 'examplepass'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: